### PR TITLE
Fixes to support new NodeJS version

### PR DESCRIPTION
**Pull request by mastepanoski**
Update of "util.debug" to "console.error" to support NodeJS LTS.
Modify socket connection to support new version (LTS and 5.x).

### CODE REVIEW

**Comment by gtjoseph** [comment]
I'm looking through this right now as well.
It might help if you didn't reformat the source file in this commit. It's hard to tell what's a format change and what's a functional change.

**Comment by mastepanoski** [comment]
I'm sorry, my editor formatted automatically the code when I saved it.
I list the changes here:

1. I replaced all ocurrences of "util.debug("  by "console.error("
2. I changed var Socket = require('net').Socket by var net = require('net');
3. I changed  api.prototype.connect with the content:

`api.prototype.connect = function(connectHandler) {
    // While logging in, if an error occurs, we should kill the socket. This will keep node from not terminating due to lingering sockets.
    if (this.debug > 3) console.error('Connecting to ' + this.host);
    this.connecting = true;
    var self = this;
    this.socket = net.connect(this.port, this.host, connectHandler);
    // This will be called if there is no activity to the server.
    // If this occurs before the login is successful, it could be
    // that it is a connection timeout.
    this.socket.setTimeout(this.timeout * 1000, function(e) { // the socket timed out. According to the NodeJS api docs, right after this, it will be._closed.
      if (self.debug)
        console.error('Socket Timeout');
      if (!self.connected)
        self.emit('error', 'Timeout Connecting to host', self);
    });
    this.socket.setKeepAlive(true);
    this.socket.on('data', function(a) {
      self.read(a);
    });
    this.socket.on('end', function(a) {
      self.socket.destroy();
      if (self.connected)
        self.handler.close(true);
    });
    this.socket.on('error', function(a) {
      if (self.debug > 1)
        util.log('Connection error: ' + a);
      self.handler.emit('error', a, this.handler)
      self.handler.close(true);
    });
  }`

That's all.

**Comment by gtjoseph** [comment]
Check the new 1.X.X branch.  I don't think we need this pull request any more.

**Comment by mastepanoski** [comment]
This pull request is not needed anymore. You're made a great rework in the 1.x.x branch. Clean code, tests, and documentation. Congratulations.

**Comment by gtjoseph** [comment]
Thanks!  Let us know if there's anything else you'd like to see added or improved.

**Pull request closed without merging**
